CREATE TABLE IF NOT EXISTS `permissions` (
  `permission_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` varchar(100) NOT NULL,
  `status` enum('active','inactive','deleted') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`permission_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=51 ;

INSERT INTO `permissions` (`permission_id`, `name`, `description`, `status`) VALUES
(2, 'Site.Content.View', 'Allow users to view the Content Context', 'active'),
(3, 'Site.Reports.View', 'Allow users to view the Reports Context', 'active'),
(4, 'Site.Settings.View', 'Allow users to view the Settings Context', 'active'),
(5, 'Site.Developer.View', 'Allow users to view the Developer Context', 'active'),
(6, 'Roles.Manage', 'Allow users to manage the user Roles', 'active'),
(7, 'Users.Manage', 'Allow users to manage the site Users', 'active'),
(8, 'Users.View', 'Allow users access to the User Settings', 'active'),
(9, 'Users.Add', 'Allow users to add new Users', 'active'),
(10, 'Database.Manage', 'Allow users to manage the Database settings', 'active'),
(11, 'Emailer.Manage', 'Allow users to manage the Emailer settings', 'active'),
(12, 'Logs.View', 'Allow users access to the Log details', 'active'),
(13, 'Logs.Manage', 'Allow users to manage the Log files', 'active'),
(14, 'Emailer.View', 'Allow users access to the Emailer settings', 'active'),
(15, 'Site.Signin.Offline', 'Allow users to login to the site when the site is offline', 'active'),
(16, 'Permissions.View', 'Allow access to view the Permissions menu unders Settings Context', 'active'),
(17, 'Permissions.Manage', 'Allow access to manage the Permissions in the system', 'active'),
(18, 'Roles.Delete', 'Allow users to delete user Roles', 'active'),
(19, 'Modules.Add', 'Allow creation of modules with the builder.', 'active'),
(20, 'Modules.Delete', 'Allow deletion of modules.', 'active'),
(21, 'Permissions.Administrator.Manage', 'To manage the access control permissions for the Administrator role.', 'active'),
(22, 'Permissions.Editor.Manage', 'To manage the access control permissions for the Editor role.', 'active'),
(24, 'Permissions.User.Manage', 'To manage the access control permissions for the User role.', 'active'),
(25, 'Permissions.Developer.Manage', 'To manage the access control permissions for the Developer role.', 'active'),
(27, 'Activities.Own.View', 'To view the users own activity logs', 'active'),
(28, 'Activities.Own.Delete', 'To delete the users own activity logs', 'active'),
(29, 'Activities.User.View', 'To view the user activity logs', 'active'),
(30, 'Activities.User.Delete', 'To delete the user activity logs, except own', 'active'),
(31, 'Activities.Module.View', 'To view the module activity logs', 'active'),
(32, 'Activities.Module.Delete', 'To delete the module activity logs', 'active'),
(33, 'Activities.Date.View', 'To view the users own activity logs', 'active'),
(34, 'Activities.Date.Delete', 'To delete the dated activity logs', 'active'),
(35, 'UI.Manage', 'Manage the Bonfire UI settings', 'active'),
(36, 'Settings.View', 'To view the site settings page.', 'active'),
(37, 'Settings.Manage', 'To manage the site settings.', 'active'),
(38, 'Activities.View', 'To view the Activities menu.', 'active'),
(39, 'Database.View', 'To view the Database menu.', 'active'),
(40, 'Migrations.View', 'To view the Migrations menu.', 'active'),
(41, 'Builder.View', 'To view the Modulebuilder menu.', 'active'),
(42, 'Roles.View', 'To view the Roles menu.', 'active'),
(43, 'Sysinfo.View', 'To view the System Information page.', 'active'),
(44, 'Translate.Manage', 'To manage the Language Translation.', 'active'),
(45, 'Translate.View', 'To view the Language Translate menu.', 'active'),
(46, 'UI.View', 'To view the UI/Keyboard Shortcut menu.', 'active'),
(49, 'Profiler.View', 'To view the Console Profiler Bar.', 'active'),
(50, 'Roles.Add', 'To add New Roles', 'active');
